FROM node:22-alpine
WORKDIR /app

RUN apk add --no-cache openssl

COPY package.json package-lock.json ./
COPY prisma ./prisma
RUN npm ci && npx prisma generate

COPY . .

ENV NODE_ENV=development
ENV PORT=4000
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 4000
CMD ["npm", "run", "start:dev"]
